export interface PathObject {
  path: number;
  name: string;
  category: "projects" | "experience" | "education" | "about" | "interests" | "generic";
  description: string;
  date?: string;
  company?: string;
  role?: string;
  items?: (string | { label: string; href?: string; sub?: boolean })[];
  entries?: { date: string; title: string }[];
  subtext?: string;
  tags?: string[];
  links?: {
    github?: string;
    instagram?: string;
    printables?: string;
    external?: string;
    label?: string;
  }[];
}

export const PATH_DATA: Record<number, PathObject> = {
  2: {
    path: 2,
    name: "Monsoon",
    category: "projects",
    description: "A thematic reskin of Dune: Imperium set in the world of Wilbur Smith's Monsoon — following the Courtney Family's adventures on the high seas along the coast of East Africa. Same engine, entirely new world.",
    tags: ["DESIGN", "GAMES"],
    links: [],
  },
  4: {
    path: 4,
    name: "Art",
    category: "interests",
    description: "Favourite Artists:",
    items: [
      "Hans Heysen",
      "Albert Namatjira",
      "Matthew Bell",
      { label: "Bateleur Eagle by Matthew Bell", href: "https://matthewbellart.co.za/", sub: true },
    ],
    links: [],
  },
  6: {
    path: 6,
    name: "Threadquarters",
    category: "projects",
    description: "Jacket",
    tags: ["SOFTWARE", "CLOTHING"],
    links: [{ github: "https://github.com/switchhoff/Threadquarters", label: "GitHub" }],
  },
  8: {
    path: 8,
    name: "Golf",
    category: "interests",
    description: "",
    items: ["HCP = 38", "Member at Berwick Montuna Golf Club"],
    links: [],
  },
  10: {
    path: 10,
    name: "Saxophone",
    category: "interests",
    description: "",
    links: [],
  },
  12: {
    path: 12,
    name: "Votemotm",
    category: "projects",
    description: "",
    items: [
      "PWAs for Team Man of the Match Voting and Fan Engagement for Victorian State League Soccer Club",
      "30+ Users across Players, Coaches, Administration and Fans",
    ],
    links: [{ github: "https://github.com/switchhoff/Votemotm", label: "GitHub" }],
  },
  14: {
    path: 14,
    name: "BeNFL",
    category: "projects",
    description: "NFL Ball",
    links: [{ github: "https://github.com/switchhoff/BeNFL", label: "GitHub" }],
  },
  16: {
    path: 16,
    name: "PawsButton",
    category: "projects",
    description: "",
    items: [
      "Shared household pet care tracker — logs feeding, walks, and care tasks across all household members",
      "Prevents double-feeding and missed meals with real-time household sync",
      "Push notifications alert the household when pets are overdue for food or a walk",
    ],
    links: [{ github: "https://github.com/switchhoff/PawsButton", label: "GitHub" }],
  },
  18: {
    path: 18,
    name: "Reading, Books",
    category: "interests",
    description: "Favourite Books",
    items: ["Brotherband Series", "Wolf of the Plains", "Courtney Series"],
    links: [],
  },
  20: {
    path: 20,
    name: "Easter Egg",
    category: "generic",
    description: "You found an Easter Egg!",
    links: [],
  },
  22: {
    path: 22,
    name: "Cave Disto",
    category: "projects",
    description: "",
    items: [
      "Waterproof, rugged laser distance measuring device built for caving — helping map unknown cave systems",
      "Fuses gyroscope, compass, and laser distance measurements into a compact, form-factor case",
      "Designed for my brother with long battery life and the durability to handle the underground environment",
    ],
    tags: ["HARDWARE", "MICROCONTROLLER"],
    links: [{ github: "https://github.com/switchhoff/CaveDisto", label: "GitHub" }],
  },
  24: {
    path: 24,
    name: "Craft",
    category: "interests",
    description: "",
    items: ["Sewing", "Embroidery", "Crochet"],
    links: [],
  },
  26: {
    path: 26,
    name: "Photography",
    category: "interests",
    description: "",
    links: [{ instagram: "https://www.instagram.com/alexhofmannphotography/", label: "@alexhofmannphotography" }],
  },
  28: {
    path: 28,
    name: "Movies",
    category: "interests",
    description: "Favourite Films",
    items: ["Ocean's Eleven", "Lord of the Rings", "Pirates of the Caribbean"],
    links: [],
  },
  30: {
    path: 30,
    name: "Multiboard",
    category: "projects",
    description: "135+ Multiboard grids 3D printed and installed across the workshop — wall-mounting tools, art, monitors, and keeping cables under control.",
    links: [{ external: "https://multibuild.io/", label: "multibuild.io" }],
  },
  32: {
    path: 32,
    name: "Shout a Round",
    category: "projects",
    description: "Beer Tracker",
    links: [],
  },
  34: {
    path: 34,
    name: "Contact",
    category: "about",
    description: "",
    links: [
      { external: "tel:+61403326837", label: "+61 403326837" },
      { external: "mailto:alexanderhofmann@outlook.com.au", label: "alexanderhofmann@outlook.com.au" },
      { external: "https://www.linkedin.com/in/hofmannalexb", label: "www.linkedin.com/in/hofmannalexb" },
    ],
  },
  36: {
    path: 36,
    name: "MiniMize",
    category: "projects",
    description: "Phone Optimizer",
    links: [{ github: "https://github.com/switchhoff/MiniMise", label: "GitHub" }],
  },
  38: {
    path: 38,
    name: "LastYear",
    category: "projects",
    description: "Calendar Project",
    tags: ["SOFTWARE", "RELATIONSHIP"],
    links: [{ github: "https://github.com/switchhoff/LastYear", label: "GitHub" }],
  },
  40: {
    path: 40,
    name: "Habitat",
    category: "projects",
    description: "A habit tracker that rewards consistency by growing virtual plants and trees — build streaks, unlock new species, and watch your garden flourish.",
    tags: ["SOFTWARE", "PERSONAL"],
    links: [{ github: "https://github.com/switchhoff/Habitat", label: "GitHub" }],
  },
  42: {
    path: 42,
    name: "World Map",
    category: "projects",
    description: "A custom world travel map built as a woodworking project — continents cut, stained, and assembled by hand on a backing board, tracking every country visited.",
    items: ["Germany", "India", "Singapore", "South Africa", "Thailand"],
    tags: ["WOODWORKING", "TRAVEL"],
    links: [],
  },
  44: {
    path: 44,
    name: "3D Printing",
    category: "projects",
    description: "CAD and 3D printing useful objects around the house — from a necklace shelf and iPad case to medication boxes, a soldering stand, and infinitely more.",
    tags: ["3D PRINTING", "DESIGN"],
    links: [{ printables: "https://www.printables.com/@AlexHofmann_3702877", label: "Printables" }],
  },
  46: {
    path: 46,
    name: "SixClicks",
    category: "projects",
    description: "Briefcase App",
    links: [{ github: "https://github.com/switchhoff/SixClicks", label: "GitHub" }],
  },
  48: {
    path: 48,
    name: "Portfolio Website",
    category: "projects",
    description: "Inspired by the point-and-click adventure games I grew up playing — every object in the workshop is a clickable hotspot telling a piece of my story.",
    tags: ["SOFTWARE", "PORTFOLIO"],
    links: [{ github: "https://github.com/switchhoff/Portfolio", label: "GitHub" }],
  },
  50: {
    path: 50,
    name: "Future Work",
    category: "experience",
    description: "TBD...",
    links: [],
  },
  52: {
    path: 52,
    name: "Tashi",
    category: "generic",
    description: "Tashi",
    links: [],
  },
  54: {
    path: 54,
    name: "Fig",
    category: "generic",
    description: "Fig",
    links: [],
  },
  56: {
    path: 56,
    name: "Beans",
    category: "generic",
    description: "Beans",
    links: [],
  },
  58: {
    path: 58,
    name: "Ron Johnston Medal Winner",
    category: "experience",
    date: "2023",
    company: "Humanitarian Innovation Hackathon",
    role: "PowerPots",
    description: "Sand filter solution for water filtration in Vanuatu through community education and innovative product prototyping.",
    tags: ["HACKATHON"],
    links: [],
  },
  60: {
    path: 60,
    name: "Winner",
    category: "experience",
    date: "2021 & 2022",
    company: "Robot Building Competition",
    role: "Winner",
    description: "Completed challenges requiring robots to line-follow specific colour segments at speed — precision engineering under competitive conditions.",
    tags: ["HACKATHON"],
    links: [],
  },
  62: {
    path: 62,
    name: "Winner",
    category: "experience",
    date: "2022",
    company: "Monash HardHack",
    role: "Winner",
    description: "Designed, built, and tested small unmanned aquatic vehicle with underwater sonar topology mapping.",
    tags: ["HACKATHON"],
    links: [],
  },
  64: {
    path: 64,
    name: "Chief Engineer",
    category: "experience",
    date: "2025 — NOW",
    company: "Fortifyedge",
    role: "Chief Engineer",
    description: "Project Lead integrating thermal sights with Team Awareness Kit (TAK) for situational awareness systems.",
    links: [],
  },
  66: {
    path: 66,
    name: "Engineer",
    category: "experience",
    date: "2022 — 2024",
    company: "DefendTex",
    role: "Engineer",
    description: "Electronics/Software Engineer developing autonomy subsystem for unmanned ground vehicle. Thermal object detection, GStreamer pipelines, ArduPilot implementation.",
    links: [],
  },
  68: {
    path: 68,
    name: "Software Systems Engineer",
    category: "experience",
    date: "2025",
    company: "Tonbo Systems",
    role: "Software Systems Engineer",
    description: "Project Lead working to integrate thermal sights with Team Awareness Kit (TAK) and deliver network-connected future soldier system kit.",
    links: [],
  },
  70: {
    path: 70,
    name: "Monash University",
    category: "education",
    description: "",
    entries: [
      { date: "2024", title: "Master of Electrical Engineering" },
      { date: "2020–2023", title: "Bachelor of Robotics and Mechatronics Engineering" },
    ],
    subtext: "Specialization: Artificial Intelligence\nMinor: Software Engineering",
    items: [
      "Dean's Honour List 2020–2023",
      "2024 Master of Engineering Academic Medal Winner",
    ],
    tags: ["UNDERGRADUATE", "POSTGRADUATE"],
    links: [],
  },
  72: {
    path: 72,
    name: "High Powered Rocketry",
    category: "education",
    date: "2022-2023",
    company: "Monash University",
    role: "Flight Systems Member",
    description: "Conducted research on non-combustible rocket deployment systems. Composite manufacturing of rocket body components.",
    links: [],
  },
  74: {
    path: 74,
    name: "Monash Uncrewed Aerial Systems",
    category: "education",
    date: "2021-2022",
    company: "Monash University",
    role: "Aerostructures Training Officer",
    description: "Sub-team manager responsible for composite manufacturing. Lead role in design and manufacture of destructive testing system.",
    links: [],
  },
  76: {
    path: 76,
    name: "Alex Hofmann",
    category: "about",
    description: "Melbourne VIC | Age 24. Engineering problem solver with passion for building things. Defence tech background across cutting-edge R&D to forward deployments. Love a challenge.",
    links: [],
  },
  78: {
    path: 78,
    name: "Melbourne Weather",
    category: "projects",
    description: "This simple project takes live Melbourne weather via the free Open Meteo API and embeds it into this website.",
    links: [],
  },
  82: {
    path: 82,
    name: "Board Games",
    category: "interests",
    description: "Favourite Games",
    items: ["Dune Imperium", "Wingspan", "Ark Nova"],
    links: [],
  },
  84: {
    path: 84,
    name: "LoverLamp",
    category: "projects",
    description: "Smart Lamp",
    links: [],
  },
  86: {
    path: 86,
    name: "BinThereStoreThat",
    category: "projects",
    description: "Storage Solution",
    links: [{ github: "https://github.com/switchhoff/BinThereStoreThat", label: "GitHub" }],
  },
  88: {
    path: 88,
    name: "Candle",
    category: "generic",
    description: "Just a Candle",
    links: [],
  },
  90: {
    path: 90,
    name: "Claude",
    category: "generic",
    description: "Coded with Claude",
    links: [],
  },
  92: {
    path: 92,
    name: "Gemini",
    category: "generic",
    description: "Coded with Gemini",
    links: [],
  },
  94: {
    path: 94,
    name: "Chair",
    category: "generic",
    description: "Just a Chair",
    links: [],
  },
  96: {
    path: 96,
    name: "Ron Johnston Medal Winner",
    category: "experience",
    date: "2023",
    company: "Humanitarian Innovation Hackathon",
    role: "Ron Johnston Medal Winner",
    description: "Bamboo roof cooling design for developing housing in Fiji. Intensive program solving real-world humanitarian issues through engineering innovation.",
    tags: ["HACKATHON"],
    links: [],
  },
};

export function getPathData(path: number): PathObject | null {
  return PATH_DATA[path] || null;
}
