export const BLOCK_MAPPINGS = {
  about: [
    { fillPath: 76, strokePath: 77 },
  ],
  interests: [
    { fillPath: 4, strokePath: 5 },
    { fillPath: 8, strokePath: 9 },
    { fillPath: 10, strokePath: 11 },
    { fillPath: 18, strokePath: 19 },
    { fillPath: 24, strokePath: 25 },
    { fillPath: 28, strokePath: 29 },
    { fillPath: 82, strokePath: 83 },
    { fillPath: 94, strokePath: 95 },
    { fillPath: 42, strokePath: 43 },
  ],
  projects: [
    { fillPath: 2, strokePath: 3 },
    { fillPath: 6, strokePath: 7 },
    { fillPath: 12, strokePath: 13 },
    { fillPath: 14, strokePath: 15 },
    { fillPath: 16, strokePath: 17 },
    { fillPath: 22, strokePath: 23 },
    { fillPath: 26, strokePath: 27 },
    { fillPath: 30, strokePath: 31 },
    { fillPath: 32, strokePath: 33 },
    { fillPath: 36, strokePath: 37 },
    { fillPath: 38, strokePath: 39 },
    { fillPath: 40, strokePath: 41 },
    { fillPath: 44, strokePath: 45 },
    { fillPath: 46, strokePath: 47 },
    { fillPath: 48, strokePath: 49 },
    { fillPath: 34, strokePath: 35 },
    { fillPath: 84, strokePath: 85 },
    { fillPath: 86, strokePath: 87 },
  ],
  education: [
    { fillPath: 70, strokePath: 71 },
    { fillPath: 72, strokePath: 73 },
    { fillPath: 74, strokePath: 75 },
  ],
  experience: [
    { fillPath: 50, strokePath: 51 },
    { fillPath: 58, strokePath: 59 },
    { fillPath: 60, strokePath: 61 },
    { fillPath: 62, strokePath: 63 },
    { fillPath: 64, strokePath: 65 },
    { fillPath: 66, strokePath: 67 },
    { fillPath: 68, strokePath: 69 },
    { fillPath: 88, strokePath: 89 },
    { fillPath: 96, strokePath: 97 },
    { fillPath: 98, strokePath: 99 },
  ],
  generic: [
    { fillPath: 20, strokePath: 21 },
    { fillPath: 52, strokePath: 53 },
    { fillPath: 54, strokePath: 55 },
    { fillPath: 56, strokePath: 57 },
    { fillPath: 78, strokePath: 79 },
    { fillPath: 80, strokePath: 81 },
    { fillPath: 90, strokePath: 91 },
    { fillPath: 92, strokePath: 93 },
  ],
};

export const CATEGORY_COLORS: Record<string, string> = {
  projects: "#FF6B6B",
  experience: "#4ECDC4",
  education: "#27ae60",
  about: "#FFA07A",
  interests: "#8e44ad",
  generic: "#CCCCCC",
};
